spring:
  datasource:
    url:
    username: admin
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql:

kakao:
  restApiKey:
  redirectUrl: http://3.34.58.178:8080/callback

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:

jwt:
  secret: